### ISSUE TITLE
Bug - Pictures being displayed "weird"

### ISSUE THREAD

**Issue by Mic-R** [gymh/elternportal-api#22]
![image](https://user-images.githubusercontent.com/86645595/126205697-336705f8-9bd7-4009-aa47-eb95c641ee5c.png)
This is how /suche/fundsachen is being displayed for me.

I disabled uBlockOrigin to see if it might be an issue, but it wasn't. So i think this is a Bug.

**Comment by philippdormann** [comment]
not sure on what you're doing 😄

the api works as designed, just ran a manual test myself.

![image](https://user-images.githubusercontent.com/17651032/126207118-1469c890-a832-48ee-af84-6962e4d54e47.png)

**Comment by philippdormann** [comment]
(content of artsoftandmore pages is none of my business and managed by the local school admins)

**Comment by Mic-R** [comment]
> not sure on what you're doing 😄
> 
> the api works as designed, just ran a manual test myself.
> 
> ![image](https://user-images.githubusercontent.com/17651032/126207118-1469c890-a832-48ee-af84-6962e4d54e47.png)

hm, why do i get this "Bild" thing then. I am kind of confused. i were not able to find any pictures. Kind of weird. Just saw the coment,didn't know where to report this to. (:

**Comment by philippdormann** [comment]
yeah, that's on the raw elternportal content (when you login with your parent's credentials)

please contact the local school admin (as seen in imprint) for fixing broken images/ contacting the vendor of elternportal.

gymh/elternportal-api works perfectly fine and is in no form associated with any vendor :)

**Comment by Mic-R** [comment]
> yeah, that's on the raw elternportal content (when you login with your parent's credentials)
> 
> please contact the local school admin (as seen in imprint) for fixing broken images/ contacting the vendor of elternportal.
> 
> gymh/elternportal-api works perfectly fine and is in no form associated with any vendor :)

This was actually my parents showing me the issue and aking me if I could fix it (as a student you are not allowed to log in by yourself).
I don't think this is that much of an issue to contact the school admin and/or art media and more GmbH.
Thank you tho!
Have a great afternoon!
